name: 'bulckan-test1'

networks:
  bulckan-test1:

services:
  apache1:
    image: httpd:latest
    ports:
      - "8085:80"
    networks:
      - bulckan-test1
    labels:
      - "com.example.description=Servidor Apache HTTP 1"
      - "com.example-test.description=Test n:5"
  
  apache2:
    image: httpd:2.4.62-alpine3.20
    ports:
      - "8086:80"
    networks:
      - bulckan-test1
    labels:
      - "com.example.description=Servidor Apache HTTP 2"
      - "com.example-test.description=Test n:5"
  
