version: '3.8'

services:
  apache1:
    image: httpd:latest
    ports:
      - "8080:80"
    labels:
      - "com.example.description=Servidor Apache HTTP 1"
      - "com.example-test.description=Test 1"