version: '3.8'

services:
  apache2:
    image: httpd:latest
    ports:
      - "8087:80"
    labels:
      - "com.example.description=Servidor Apache HTTP 3"
      - "com.example-test.description=Test n:4"